### ISSUE TITLE
Publicação Jacarei

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preservCutGeo-BR2021#13]
Feito
https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Jacarei/_pk0145.01
ps. os dados estão um pouco deslocados em relação ao bing

**Comment by 0e1** [comment]
Aprovado.

Fiz a geração dos arquivos filtrados, adicionei o size no make_conf e atualizei o readme.

Atualizei o site, visualizar em http://addressforall.org/pt/visualization/ e testar os arquivos filtrados em http://addressforall.org/pt/downloads/.

Os dados ingestados **não** precisam mais ser mantidos na ingest utilizada no processo de ingestão.
