### ISSUE TITLE
Novo Hamburgo

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preservCutGeo-BR2021#14]
Novo dado publicado https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/RS/NovoHamburgo

**Comment by 0e1** [comment]
Dados publicados.

**Comment by ppKrauss** [comment]
@0e1 , temos ainda falha nos metadados, não publicou o `reproducibility.sh`  em  https://github.com/digital-guard/preserv-BR/tree/main/data/RS/NovoHamburgo/_pk0063.01

**Comment by 0e1** [comment]
Estou republicando dados. reproducibility e readme seriam comitados junto com os demais que estou gerando. Porém, Carlos já comitou o script.
