### ISSUE TITLE
Padrão OpenStreetMap em Contagem e Jundiaí

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preservCutGeo-BR2021#15]
Foi solicitado que em [MG/Contagem/_pk0009.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/MG/Contagem/_pk0009.01) e [SP/Jundiai/_pk0025.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Jundiai/_pk0025.01),  preservados conforme [MG/Contagem/_pk0009.01](https://github.com/digital-guard/preserv-BR/blob/main/data/MG/Contagem/_pk0009.01/make_conf.yaml) e [SP/Jundiai/_pk0025.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Jundiai/_pk0025.01/make_conf.yaml), fosse quebrada a _key_ `address` em `addr:street` e `addr:housenumber` e que fosse utilizado o padrão OpenStreetMap para as demais tags.

**Comment by 0e1** [comment]
Essa solicitação deve mudar o processo de publicação, de maneira que seja usado por default o padrão OpenStreetMap.
Consolidado do de-para A4A<->OSM está em https://docs.google.com/spreadsheets/d/13Rxw7ry9bU2tpg1jUaeoGXWP5Vn2wr0Uw3AGo6zyMsg/edit#gid=644252560.

Por hora apenas os dois casos solicitados.

A estratégia escolhida foi usar o [sed](https://www.gnu.org/software/sed/).

**Comment by 0e1** [comment]
Para o caso de [MG/Contagem/_pk0009.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/MG/Contagem/_pk0009.01) foi adotado as seguintes substituições.

```sh
sed -i "s/\"via\": \"\(.*\)\"/\"name\": \"\1\"/g" via/lns_*.geojson

sed -i "s/\"nsvia\": \"\(.*\)\"/\"addr:suburb\": \"\1\"/g" parcel/pols_*.geojson
sed -i "s/\"address\": \"\(\?\)\, \(\?\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\"/g" parcel/pols_*.geojson
sed -i "s/\"address\": \"\(.*\)\, \(\?\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\"/g" parcel/pols_*.geojson
sed -i "s/\"address\": \"\(\?\)\, \(.*\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\2\"/g" parcel/pols_*.geojson
sed -i "s/\"address\": \"\(.*\)\, \(.*\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\2\"/g" parcel/pols_*.geojson


sed -i "s/\"address\": \"\(\?\)\, \(\?\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\(.*\)\, \(\?\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\(\?\)\, \(.*\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\2\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\(.*\)\, \(.*\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\2\"/g" geoaddress/pts_*.geojson
```

Para o caso de [SP/Jundiai/_pk0025.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Jundiai/_pk0025.01) foi aplicado as seguintes substituições:

```sh
sed -i "s/\"nsvia\": \"\(.*\)\"/\"name\": \"\1\"/g" nsvia/pols_*.geojson

sed -i "s/\"via\": \"\(.*\)\"/\"name\": \"\1\"/g" via/lns_*.geojson

sed -i "s/\"address\": \"\(\?\)\, \(\?\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\([^\"]*\)\, \(\?\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\(\?\)\, \([^\"]*\)\"/\"addr:street\":\"\"\,\"addr:housenumber\":\"\2\"/g" geoaddress/pts_*.geojson
sed -i "s/\"address\": \"\([^\"]*\)\, \([^\"]*\)\"/\"addr:street\":\"\1\"\,\"addr:housenumber\":\"\2\"/g" geoaddress/pts_*.geojson

sed -i "s/\"nsvia\": \"\([^\"]*\)\"/\"addr:suburb\": \"\1\"/g" geoaddress/pts_*.geojson

sed -i "s/\"postcode\": \"\([^\"]*\)\"/\"addr:postcode\": \"\1\"/g" geoaddress/pts_*.geojson
```

**Comment by 0e1** [comment]
@IgorEliezer 

Por favor avalie alguns arquivos dos layers em [MG/Contagem/_pk0009.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/MG/Contagem/_pk0009.01) e [SP/Jundiai/_pk0025.01](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Jundiai/_pk0025.01) que interessam a você. Todos devem estar usando o padrão OpenStreetMap onde couber.

**Comment by IgorEliezer** [comment]
É possível mudar o case dos textos de `addr:street` de Contagem no CutGeo para Camel Case?

![image](https://github.com/digital-guard/preservCutGeo-BR2021/assets/4673289/d7b0a054-338a-4846-9c03-f869c929b602)

Porque o pessoal que vai testar no OSM, precisa já ter os textos pelo menos 90% certo. Aí os casos de "Do", "Da" etc, pode ser arrumado manualmente e, no nosso lado, fica para um refinamento posterior.

--- 

Vi os eixos de Jundiaí, também precisa mudar o case do nome das vias, pelo menos.

![image](https://github.com/digital-guard/preservCutGeo-BR2021/assets/4673289/237bdfcb-080f-42d9-8140-4f88de60ea0f)

Os arquivos CutGeo precisam seguir o mesmo padrão OSM, não só quanto às tags, mas também ao text case e desabreviação, uma vez que serão usados no OSM.

**Comment by 0e1** [comment]
É possível sim.

Como disse em https://github.com/digital-guard/preserv/issues/147#issuecomment-1739975869, até o momento os repositórios CutGeo são para os arquivos _filtrados_, resultados da ingestão e de processos automatizados que tem como base o make_conf.yaml.

Ao remover abreviação/trocar case/remover campos lixo etc, deixam de ser filtrados.
Além disso, features com erro também irão para o CutGeo, da mesma forma que vão para a ESRI.

@ppKrauss dar o 'ok' aqui.

**Comment by IgorEliezer** [comment]
> Como disse em [digital-guard/preserv#147 (comment)](https://github.com/digital-guard/preserv/issues/147#issuecomment-1739975869), até o momento os repositórios CutGeo são para os arquivos _filtrados_, resultados da ingestão e de processos automatizados que tem como base o make_conf.yaml.

Também pensei em algo assim, que filtrados são dados selecionados sem alteração. Mas por causa da apresentação, a gente abre uma exceção pra estas duas cidades. Pelo menos já vamos vendo o que precisa ser feito para uma padronização definitiva para o futuro.

**Comment by 0e1** [comment]
@IgorEliezer 

Pronto. Dados de Contagem e Jundiaí atualizados.

Observações:

- Campos que não tem **alias** em [campos padronizados](https://wiki.addressforall.org/doc/dg:AsIs_feature_types#Campos_padronizados) **não estarão** presentes nas propriedades do geojson. **Exceto** `sup` (que não tem alias, mas é complemento do endereço e me parece melhor deixar o mapeador decidir se usa ou não a informação). Se o mapeador não quiser usar, no editor OSM apropriado ele pode selecionar todos os elementos e apagar o `sup` em lote. Evidentemente, também posso remover `sup` do CutGeo. 


- Foi criada uma função para exportar para OpenStreetMap, que por hora não foi integrada no processo de publicação;

- Foi mesclado o conteúdo de _feature_asis_ e _feature_asis_discarded_ nessa função. Porém, nem tudo em _feature_asis_discarded_ possui `kx_ghs9`. Sem ele não dá pra publicar em CutGeo. Ver [kx_ghs9-em-feature_asis_discarded](https://github.com/digital-guard/preserv/wiki/Consolida%C3%A7%C3%A3o#kx_ghs9-em-feature_asis_discarded). Além disso, tive que aplicar [ST_MakeValid](https://postgis.net/docs/ST_MakeValid.html) para ser possível publicar geometrias de bairros de Jundiaí que possuem [error](https://wiki.addressforall.org/doc/dg:AsIs_feature_types#Error_mask) não-nulo;

- Apesar da mescla, [error](https://wiki.addressforall.org/doc/dg:AsIs_feature_types#Error_mask) não aparecerá no CutGeo (assim como qualquer outro campo sem um alias), seguindo o que é feito na ESRI;

- Apliquei _desabreviação_ e _ajuste do case_ nos dados em _feature_asis_discarded_ conforme https://github.com/digital-guard/preserv/wiki/Consolida%C3%A7%C3%A3o#ingestfeature_asis_discarded. Processo manual;

- **Não foi corrigido** casos onde a preposição está no lugar errado (Posso corrigir? Sim, posso. Leva tempo.). Acredito que isso possa servir de motivo para mostrar como usar um editor para selecionar e corrigir em lote pequenos problemas nos dados objeto de importação)

**Comment by IgorEliezer** [comment]
> * **Não foi corrigido** casos onde a preposição está no lugar errado (Posso corrigir? Sim, posso. Leva tempo.). Acredito que isso possa servir de motivo para mostrar como usar um editor para selecionar e corrigir em lote pequenos problemas nos dados objeto de importação)

Isso pode ficar com prioridade baixa ou postergado já que fizemos a apresentação semana passada. Acredito que podemos tolerar determinados erros, dentro de uma margem aceitável, e colocaríamos uma nota no material avisando que as correções são feitas de forma generalista e cabe ao usuário ter discernimento e fazer verificação manual caso a caso.

**Comment by 0e1** [comment]
Vou encerrar essa issue. Se necessário seguir a discussão em https://github.com/digital-guard/preserv/issues/153.
