### ISSUE TITLE
Publicação de Bage

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preservCutGeo-BR2021#8]
https://github.com/digital-guard/preservCutGeo-BR2021/tree/bage-20221030/data/RS/Bage

**Comment by ppKrauss** [comment]
Bug menor de UTF8, ver por exemplo https://github.com/digital-guard/preservCutGeo-BR2021/blob/bage-20221030/data/RS/Bage/via/distrib_viaName_ghs.csv

![image](https://user-images.githubusercontent.com/1651447/198967611-28f7dd57-f6f8-4dee-9095-2e762569cbc6.png)

**Comment by crebollobr** [comment]
Correção automática.
Tem alguns nomes sem acento e aparentemente erradas, se precisar corrigir teria que ser feito manualmente

Novo branch
https://github.com/digital-guard/preservCutGeo-BR2021/tree/bage-20221102/data/RS/Bage/_pk0082.01

**Comment by 0e1** [comment]
Em qual _base de dados_ foi feita a ingestão? Ela ainda existe?

O passo [Copiar informações para DL03t_main](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#copiar-informa%C3%A7%C3%B5es-para-dl03t_main) foi executado antes de deletar a _base de dados_ onde foi feita a ingestão?

**Comment by crebollobr** [comment]
Foi feita na ingest20. Não existe mais, todo trabalho refaço essa base. 
Tem tambem o problema do espaço no servidor, o banco de dados pode chegar a mais de 1GB.

**Comment by 0e1** [comment]
Não executar o [passo](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#copiar-informa%C3%A7%C3%B5es-para-dl03t_main), implica em retrabalho se apagar a ingest. Não entendo o motivo de não executá-lo uma vez que ele está escrito em fluxo de trabalho já estabelecido na wiki e via email.

**Comment by crebollobr** [comment]
Por favor, indicar o link da documentação

**Comment by 0e1** [comment]
Informado nos comentários acima.
E lembrete também via email.

**Comment by ppKrauss** [comment]
* @0e1 indicar novamente o link aqui na issue
* @crebollobr indicar exatamente o que está ruim na documentação para podermos corrigir. Se não houverem correções, testar e fechar a *issue*.

**Comment by crebollobr** [comment]
A documentação está OK,
Precisa fazer merge dos dados se estiverem OK

**Comment by 0e1** [comment]
- Refiz o processo de ingestão para gerar novamente os dados necessários (ver https://github.com/digital-guard/preserv/blob/main/docs/pt/publication.md).
- Comparei amostra de arquivos gerados com arquivos na branch, pra ver se mosaico era diferente.
- Atualizei o CutGeo. Mantive os arquivos publicados na branch.
- Gerei os arquivos csv e shp dos dados filtrados.

- Atualizei listas, ver:
   - http://addressforall.org/teste2/
   - http://addressforall.org/pt/visualization/
   - http://addressforall.org/pt/downloads/
   - https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byHash.md
   - https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byJurisdic.md
